# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x10serverless.model\"5\n\x0ePredictRequest\x12\x10\n\x08meta_key\x18\x01 \x01(\t\x12\x11\n\tsequences\x18\x02 \x03(\x05\"!\n\x0fPredictResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32Y\n\x05Model\x12P\n\x07Predict\x12 .serverless.model.PredictRequest\x1a!.serverless.model.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PREDICTREQUEST']._serialized_start=33
  _globals['_PREDICTREQUEST']._serialized_end=86
  _globals['_PREDICTRESPONSE']._serialized_start=88
  _globals['_PREDICTRESPONSE']._serialized_end=121
  _globals['_MODEL']._serialized_start=123
  _globals['_MODEL']._serialized_end=212
# @@protoc_insertion_point(module_scope)
